name: CI

on:
  push:
    branches:
      - "**"

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: applitools-install
        uses: colbyfayock/applitools-eyes-action@main
        with:
          APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
          baseUrl: https://demo.applitools.com/
      - run: npm ci
      - name: Run Tests
        run: npm run test
